name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: nuniesmith/fks_actions/.github/workflows/ci-python-service.yml@main
    with:
      service_name: stocks
      service_port: "8016"
      python_version: "3.12"
      healthcheck_enabled: true
      healthcheck_path: "/health"
      has_dev_requirements: true
      run_mypy: true
      dockerfile_path: "./docker/Dockerfile"
      cleanup_disk: false
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
